# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatialmaps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_name',
            new_name='title',
        ),
    ]
